name: Build subtitles
on:
  push:
    paths:
      - "assets/subs/**"
      - "scripts/generate-subs-from-folder.mjs"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate subtitles
        run: node scripts/generate-subs-from-folder.mjs

      - name: Commit changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "🤖 OnePace Builder"
            git config user.email "actions@users.noreply.github.com"
            git add subtitles/series
            git commit -m "chore: regenerate subtitles"
            git push
          else
            echo "No changes."
          fi
